config/routes.rb
Rails.application.routes.draw do
  resources :affars
  resources :koncepts
  resources :kedjas
  resources :excel_to_model_mappings
  resources :uploaded_files
  resources :products
  resources :custom_campaigns
  get 'welcome/index'

  resources :people
  resources :companies

  root 'welcome#index'

end

app/models/excel_to_model_mapping.rb
class ExcelToModelMapping < ActiveRecord::Base
end

app/controllers/excel_to_model_mappings_controller.rb
class ExcelToModelMappingsController < ApplicationController
  before_action :set_excel_to_model_mapping, only: [:show, :edit, :update, :destroy]

  # GET /excel_to_model_mappings
  # GET /excel_to_model_mappings.json
  def index
    @excel_to_model_mappings = ExcelToModelMapping.all
  end

  # GET /excel_to_model_mappings/1
  # GET /excel_to_model_mappings/1.json
  def show
  end

  # GET /excel_to_model_mappings/new
  def new
    @excel_to_model_mapping = ExcelToModelMapping.new

    # Load all models
    Rails.application.eager_load! # Not loaded by default in development mode
    @available_models = ActiveRecord::Base.descendants
   
  end

  # GET /excel_to_model_mappings/1/edit
  def edit
  end

  # POST /excel_to_model_mappings
  # POST /excel_to_model_mappings.json
  def create
    @excel_to_model_mapping = ExcelToModelMapping.new(excel_to_model_mapping_params)

    respond_to do |format|
      if @excel_to_model_mapping.save
        format.html { redirect_to @excel_to_model_mapping, notice: 'Excel to model mapping was successfully created.' }
        format.json { render :show, status: :created, location: @excel_to_model_mapping }
      else
        format.html { render :new }
        format.json { render json: @excel_to_model_mapping.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /excel_to_model_mappings/1
  # PATCH/PUT /excel_to_model_mappings/1.json
  def update
    respond_to do |format|
      if @excel_to_model_mapping.update(excel_to_model_mapping_params)
        format.html { redirect_to @excel_to_model_mapping, notice: 'Excel to model mapping was successfully updated.' }
        format.json { render :show, status: :ok, location: @excel_to_model_mapping }
      else
        format.html { render :edit }
        format.json { render json: @excel_to_model_mapping.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /excel_to_model_mappings/1
  # DELETE /excel_to_model_mappings/1.json
  def destroy
    @excel_to_model_mapping.destroy
    respond_to do |format|
      format.html { redirect_to excel_to_model_mappings_url, notice: 'Excel to model mapping was successfully destroyed.' }
      format.json { head :no_content }
    end
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_excel_to_model_mapping
      @excel_to_model_mapping = ExcelToModelMapping.find(params[:id])
    end

    # Never trust parameters from the scary internet, only allow the white list through.
    def excel_to_model_mapping_params
      params.require(:excel_to_model_mapping).permit(:model, :excel_kolumn_titel, :model_attribute)
    end
end

app/helpers/excel_to_model_mappings_helper.rb
module ExcelToModelMappingsHelper
end

app/views/excel_to_model_mappings/_form.html.erb
<%= bootstrap_form_for(@excel_to_model_mapping, layout: :horizontal, label_col: "col-sm-2", control_col: "col-sm-10") do |f| %>
<% if @excel_to_model_mapping.errors.any? %>
<div id="error_explanation">
  <h2><%= pluralize(@excel_to_model_mapping.errors.count, "error") %> prohibited this excel_to_db_mapping from being saved:</h2>
  <ul>
    <% @excel_to_model_mapping.errors.full_messages.each do |message| %>
    <li><%= message %></li>
    <% end %>
  </ul>
</div>
<% end %>
<% @available_models = @available_models.select { |model| !(model.to_s.include? "::" or model.to_s.include? "#")} %>
<% models_for_select = @available_models.map { |model| [model.to_s, model.to_s]} %>
<%= f.select(:model, models_for_select)  %>

<%= f.text_field :excel_kolumn_titel, label: "Excel kolumn titel" %>
<%= f.text_field :model_attribute, label: "Model attribute" %>
<%= f.submit %>
</div>
<% end %>

app/views/excel_to_model_mappings/edit.html.erb
<h1>Editing Excel To Model Mapping</h1>

<%= render 'form' %>

<%= link_to 'Show', @excel_to_model_mapping %> |
<%= link_to 'Back', excel_to_model_mappings_path %>

app/views/excel_to_model_mappings/index.html.erb
<p id="notice"><%= notice %></p>

<h1>Listing Excel To Model Mappings</h1>

<table class="table table-striped table-hover">
  <thead>
    <tr>
      <th>Model</th>
      <th>Excel kolumn titel</th>
      <th>Model attribute</th>
      <th colspan="3"></th>
    </tr>
  </thead>

  <tbody>
    <% @excel_to_model_mappings.each do |excel_to_model_mapping| %>
      <tr class="acive">
        <td><%= excel_to_model_mapping.model %></td>
        <td><%= excel_to_model_mapping.excel_kolumn_titel %></td>
        <td><%= excel_to_model_mapping.model_attribute %></td>
        <td><%= link_to 'Show', excel_to_model_mapping %></td>
        <td><%= link_to 'Edit', edit_excel_to_model_mapping_path(excel_to_model_mapping) %></td>
        <td><%= link_to 'Destroy', excel_to_model_mapping, method: :delete, data: { confirm: 'Are you sure?' } %></td>
      </tr>
    <% end %>
  </tbody>
</table>

<br>

<%= link_to 'New Excel to model mapping', new_excel_to_model_mapping_path %>

app/views/excel_to_model_mappings/new.html.erb
<h1>New Excel To Model Mapping</h1>

<%= render 'form' %>

<%= link_to 'Back', excel_to_model_mappings_path %>

app/views/excel_to_model_mappings/show.html.erb
<p id="notice"><%= notice %></p>

<p>
  <strong>Model:</strong>
  <%= @excel_to_model_mapping.model %>
</p>

<p>
  <strong>Excel kolumn titel:</strong>
  <%= @excel_to_model_mapping.excel_kolumn_titel %>
</p>

<p>
  <strong>Model attribute:</strong>
  <%= @excel_to_model_mapping.model_attribute %>
</p>

<%= link_to 'Edit', edit_excel_to_model_mapping_path(@excel_to_model_mapping) %> |
<%= link_to 'Back', excel_to_model_mappings_path %>