config/routes.rb
Rails.application.routes.draw do
  resources :affars
  resources :koncepts
  resources :kedjas
  resources :excel_to_model_mappings
  resources :uploaded_files
  resources :products
  resources :custom_campaigns
  get 'welcome/index'

  resources :people
  resources :companies

  root 'welcome#index'

end

app/models/koncept.rb
class Koncept < ActiveRecord::Base
  belongs_to :kedja
end

app/controllers/koncepts_controller.rb
class KonceptsController < ApplicationController
  before_action :set_koncept, only: [:show, :edit, :update, :destroy]

  # GET /koncepts
  # GET /koncepts.json
  def index
    @koncepts = Koncept.all
  end

  # GET /koncepts/1
  # GET /koncepts/1.json
  def show
  end

  # GET /koncepts/new
  def new
    @koncept = Koncept.new
  end

  # GET /koncepts/1/edit
  def edit
  end

  # POST /koncepts
  # POST /koncepts.json
  def create
    @koncept = Koncept.new(koncept_params)

    respond_to do |format|
      if @koncept.save
        format.html { redirect_to @koncept, notice: 'Koncept was successfully created.' }
        format.json { render :show, status: :created, location: @koncept }
      else
        format.html { render :new }
        format.json { render json: @koncept.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /koncepts/1
  # PATCH/PUT /koncepts/1.json
  def update
    respond_to do |format|
      if @koncept.update(koncept_params)
        format.html { redirect_to @koncept, notice: 'Koncept was successfully updated.' }
        format.json { render :show, status: :ok, location: @koncept }
      else
        format.html { render :edit }
        format.json { render json: @koncept.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /koncepts/1
  # DELETE /koncepts/1.json
  def destroy
    @koncept.destroy
    respond_to do |format|
      format.html { redirect_to koncepts_url, notice: 'Koncept was successfully destroyed.' }
      format.json { head :no_content }
    end
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_koncept
      @koncept = Koncept.find(params[:id])
    end

    # Never trust parameters from the scary internet, only allow the white list through.
    def koncept_params
      params.require(:koncept).permit(:namn, :kedja_id)
    end
end

app/helpers/koncepts_helper.rb
module KonceptsHelper
end

app/views/koncepts/_form.html.erb
<%= bootstrap_form_for(@koncept, layout: :horizontal, label_col: "col-sm-2", control_col: "col-sm-10") do |f| %>
  <% if @koncept.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(@koncept.errors.count, "error") %> prohibited this koncept from being saved:</h2>

      <ul>
      <% @koncept.errors.full_messages.each do |message| %>
        <li><%= message %></li>
      <% end %>
      </ul>
    </div>
  <% end %>

    <%= f.collection_select(:kedja_id, Kedja.all, :id, :namn, {include_blank: true}) %>
    <%= f.text_field :namn %>
    <%= f.submit %>
<% end %>

app/views/koncepts/edit.html.erb
<h1>Editing Koncept</h1>

<%= render 'form' %>

<%= link_to 'Show', @koncept %> |
<%= link_to 'Back', koncepts_path %>

app/views/koncepts/index.html.erb
<p id="notice"><%= notice %></p>

<h1>Listing Koncepts</h1>

<table class="table table-striped table-hover">
  <thead>
    <tr>
      <th>Namn</th>
      <th>Kedja</th>
      <th colspan="3"></th>
    </tr>
  </thead>

  <tbody>
    <% @koncepts.each do |koncept| %>
      <tr class="active">
        <td><%= koncept.namn %></td>
        <td><%= koncept.kedja %></td>
        <td><%= link_to 'Show', koncept %></td>
        <td><%= link_to 'Edit', edit_koncept_path(koncept) %></td>
        <td><%= link_to 'Destroy', koncept, method: :delete, data: { confirm: 'Are you sure?' } %></td>
      </tr>
    <% end %>
  </tbody>
</table>

<br>

<%= link_to 'New Koncept', new_koncept_path %>

app/views/koncepts/new.html.erb
<h1>New Koncept</h1>

<%= render 'form' %>

<%= link_to 'Back', koncepts_path %>

app/views/koncepts/show.html.erb
<p id="notice"><%= notice %></p>

<p>
  <strong>Namn:</strong>
  <%= @koncept.namn %>
</p>

<p>
  <strong>Kedja:</strong>
  <%= @koncept.kedja %>
</p>

<%= link_to 'Edit', edit_koncept_path(@koncept) %> |
<%= link_to 'Back', koncepts_path %>