config/routes.rb
Rails.application.routes.draw do
  resources :affars
  resources :koncepts
  resources :kedjas
  resources :excel_to_model_mappings
  resources :uploaded_files
  resources :products
  resources :custom_campaigns
  get 'welcome/index'

  resources :people
  resources :companies

  root 'welcome#index'

end

app/models/custom_campaign.rb
class CustomCampaign < ActiveRecord::Base
  belongs_to :company
  belongs_to :customer_responsible, :foreign_key => "customer_responsible_id", :class_name => "Person"
  belongs_to :internal_responsible, :foreign_key => "internal_responsible_id", :class_name => "Person"

  has_and_belongs_to_many :affars
  has_and_belongs_to_many :products
end

app/controllers/custom_campaigns_controller.rb
class CustomCampaignsController < ApplicationController
  before_action :set_custom_campaign, only: [:show, :edit, :update, :destroy]

  # GET /custom_campaigns
  # GET /custom_campaigns.json
  def index
    @custom_campaigns = CustomCampaign.all
  end

  # GET /custom_campaigns/1
  # GET /custom_campaigns/1.json
  def show
  end

  # GET /custom_campaigns/new
  def new
    @custom_campaign = CustomCampaign.new
  end

  # GET /custom_campaigns/1/edit
  def edit
  end

  # POST /custom_campaigns
  # POST /custom_campaigns.json
  def create
    @custom_campaign = CustomCampaign.new(custom_campaign_params)

    respond_to do |format|
      if @custom_campaign.save
        format.html { redirect_to @custom_campaign, notice: 'Custom campaign was successfully created.' }
        format.json { render :show, status: :created, location: @custom_campaign }
      else
        format.html { render :new }
        format.json { render json: @custom_campaign.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /custom_campaigns/1
  # PATCH/PUT /custom_campaigns/1.json
  def update
    respond_to do |format|
      if @custom_campaign.update(custom_campaign_params)
        format.html { redirect_to @custom_campaign, notice: 'Custom campaign was successfully updated.' }
        format.json { render :show, status: :ok, location: @custom_campaign }
      else
        format.html { render :edit }
        format.json { render json: @custom_campaign.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /custom_campaigns/1
  # DELETE /custom_campaigns/1.json
  def destroy
    @custom_campaign.destroy
    respond_to do |format|
      format.html { redirect_to custom_campaigns_url, notice: 'Custom campaign was successfully destroyed.' }
      format.json { head :no_content }
    end
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_custom_campaign
      @custom_campaign = CustomCampaign.find(params[:id])
    end

    # Never trust parameters from the scary internet, only allow the white list through.
    def custom_campaign_params
      params.require(:custom_campaign).permit(:name, :description, :company_id, :start_date, :end_date, :notes, :num_images_required)
    end
end

app/helpers/custom_campaigns_helper.rb
module CustomCampaignsHelper
end

app/views/custom_campaigns/_form.html.erb
<%= bootstrap_form_for(@custom_campaign, layout: :horizontal, label_col: "col-sm-2", control_col: "col-sm-10") do |f| %>
<% if @custom_campaign.errors.any? %>
<div id="error_explanation">
	<h2><%= pluralize(@custom_campaign.errors.count, "error") %> prohibited this custom_campaign from being saved:</h2>
	<ul>
		<% @custom_campaign.errors.full_messages.each do |message| %>
		<li><%= message %></li>
		<% end %>
	</ul>
</div>
<% end %>
<%= f.text_field :name %><br>
<%= f.text_area :description %>
<%= f.text_field :company_id %>
<%= f.collection_select(:customer_responsible_id, Person.all, :id, :first_name, {include_blank: true}) %>
<%= f.collection_select(:internal_responsible_id, Person.all, :id, :first_name, {include_blank: true}) %>
<%= f.date_select :start_date %>
<%= f.date_select :end_date %>
<%= f.text_area :notes %>
<%= f.number_field :num_images_required, label: "Antal bilder" %>
<%= f.static_control label: "Affärer" do %>
<div class="container-fluid">
	<div class="row">
		<input type="hidden" id="shopIds" />
		<button type="button" class="btn btn-primary" data-toggle="modal" id="selectShopsBtn" data-target="#shopSelectorDialog">L&auml;gg till Aff&auml;rer</button>
	</div>
	
	<div class="row">
		<div class="panel panel-default">
			<div class="panel-body">
				<table id="datagrid-selected" class="table table-condensed table-hover table-striped" data-toggle="bootgrid" data-ajax="true" data-url="/shops/">
					<thead>
						<tr>
							<th data-column-id="id" data-type="numeric"  data-identifier="true" data-visible="false">id</th>
							<th data-column-id="shop_chains.name" data-formatter="nestedValueGetter" data-sortable="true">Kedja</th>
							<th data-column-id="shop_concepts.name" data-formatter="nestedValueGetter" data-sortable="true">Koncept</th>
							<th data-column-id="shops.name" data-formatter="nestedValueGetter" data-sortable="true">Aff&auml;r</th>
						</tr>
					</thead>
				</table>
			</div>
		</div>
	</div>
</div>
<% end %>
<%= f.collection_select(:shops, ShopConcept.all, :id, :name, {}, {:multiple => true, :size => 15}) %>
<%= f.submit %>
<% end %>


<div class="modal fade bs-example-modal-lg" role="dialog" aria-labelledby="addShopsModal" id="shopSelectorDialog">
	<div class="modal-dialog modal-lg" role="document">
		<div class="modal-content">
			<div class="modal-header">
				<button type="button" class="close" data-dismiss="modal" aria-label="Close"><span aria-hidden="true">&times;</span></button>
				<h4 class="modal-title" id="gridSystemModalLabel">V&auml;lj Aff&auml;rer</h4>
			</div>
			<div class="modal-body">
				
				<div class="container-fluid">
					<div class="row">
						
						<div class="panel panel-default">
							<div class="panel-heading">Filter</div>
							<div class="panel-body">
								<div class="container-fluid">
									<form>
										<div class="row">
											<div class="form-group col-md-4">
												<label for="filterChain">Kedja</label>
												<%= collection_select(:custom_campaign, :shops, ShopChain.all, :id, :name, {:prompt => "-"}, {:class => "form-control", :id => "filterChain"}) %>
												
												
											</div>
											<div class="form-group col-md-4">
												<label for="filterConcept">Koncept</label>
												<%= collection_select(:custom_campaign, :shops, ShopConcept.all, :id, :name, {:prompt => "-"}, {:class => "form-control", :id => "filterConcept"}) %>
												
												
											</div>
											<div class="form-group col-md-4">
												<label for="filterShop">Aff&auml;r</label>
												<%= collection_select(:custom_campaign, :shops, Shop.all, :id, :name, {:prompt => "-"}, {:class => "form-control", :id => "filterShop"}) %>
												
											</div>
											
										</div>
										<div class="row text-right">
											<input type="button" class="btn btn-default" id="removefilterBtn" value="Ta bort filtrering" />
											<input type="button" class="btn btn-default" id="filterBtn" value="Filtrera" />
										</div>
									</form>
								</div>
							</div>
						</div>
					</div>
					<div class="row">
						
						<table id="datagrid-toSelect" class="table table-condensed table-hover table-striped" data-toggle="bootgrid">
							<thead>
								<tr>
									<th data-column-id="id" data-type="numeric"  data-identifier="true" data-visible="false">id</th>
									<th data-column-id="shop_chains.name" data-formatter="nestedValueGetter" data-sortable="true">Kedja</th>
									<th data-column-id="shop_concepts.name" data-formatter="nestedValueGetter" data-sortable="true">Koncept</th>
									<th data-column-id="shops.name" data-formatter="nestedValueGetter" data-sortable="true">Aff&auml;r</th>
								</tr>
							</thead>
						</table>
					</div>
					<div class="row text-right">
						<input type="button" class="btn btn-default" id="addShopsBtn" value="Lägg aff&auml;rer" disabled="true" />
					</div>
					
				</div>
			</div>
			
			<div class="modal-footer">
				<button type="button" class="btn btn-default" data-dismiss="modal">St&auml;ng</button>
			</div>
			</div>
			</div>
			</div>
			<script>
			$("#selectShopsBtn").click(function() {
				loadDatagrids();
			});
			
			$("#filterBtn").click(function() {
				var chain = $("#filterChain").val();
				var concept = $("#filterConcept").val();
				var shop = $("#filterShop").val();
				var searchStr = (chain !== "" ? "shop_chains.id=" + chain + "|" : "") + (concept !== "" ? "shop_concepts.id=" + concept + "|" : "") + (shop !== "" ? "id=" + shop : "" );
				$("#datagrid-toSelect").bootgrid("search", searchStr);
			});

			$("#removefilterBtn").click(function() {
				resetFilters();
				$("#datagrid-toSelect").bootgrid("search", "");
			});
			
			function resetFilters() {
				$("#filterChain").prop("selectedIndex", 0);
				$("#filterConcept").prop("selectedIndex", 0);
				$("#filterShop").prop("selectedIndex", 0);
			}

			$("#addShopsBtn").click(function() {
				var selectedRows = $("#datagrid-toSelect").bootgrid("getSelectedRows");
				$("#shopIds").val(selectedRows.join(","));
				$("#datagrid-selected").bootgrid("search", "id=" + $("#shopIds").val());
				setButtonDisableStatus("addShopsBtn", true);
				
			});

			function setButtonDisableStatus(id, isDisabled) {
				$("#" + id).prop("disabled", isDisabled);	
			}


			</script>

app/views/custom_campaigns/edit.html.erb
<div class="panel panel-default">
<div class="panel-heading"><h3>Editing Custom Campaign<h3></div>
  <div class="panel-body">
<%= render 'form' %>

  </div>
</div>

<%= link_to 'Show', @custom_campaign %> |
<%= link_to 'Back', custom_campaigns_path %>

app/views/custom_campaigns/index.html.erb
<p id="notice"><%= notice %></p>

<h1>Listing Custom Campaigns</h1>

<table>
  <thead>
    <tr>
      <th>Name</th>
      <th>Description</th>
      <th>Company</th>
      <th>Start date</th>
      <th>End date</th>
      <th>Notes</th>
      <th>Num images required</th>
      <th colspan="3"></th>
    </tr>
  </thead>

  <tbody>
    <% @custom_campaigns.each do |custom_campaign| %>
      <tr>
        <td><%= custom_campaign.name %></td>
        <td><%= custom_campaign.description %></td>
        <td><%= custom_campaign.company %></td>
        <td><%= custom_campaign.start_date %></td>
        <td><%= custom_campaign.end_date %></td>
        <td><%= custom_campaign.notes %></td>
        <td><%= custom_campaign.num_images_required %></td>
        <td><%= link_to 'Show', custom_campaign %></td>
        <td><%= link_to 'Edit', edit_custom_campaign_path(custom_campaign) %></td>
        <td><%= link_to 'Destroy', custom_campaign, method: :delete, data: { confirm: 'Are you sure?' } %></td>
      </tr>
    <% end %>
  </tbody>
</table>

<br>

<%= link_to 'New Custom campaign', new_custom_campaign_path %>

app/views/custom_campaigns/new.html.erb
<div class="panel panel-default">
<div class="panel-heading"><h3>New Custom Campaign<h3></div>
  <div class="panel-body">
<%= render 'form' %>

  </div>
</div>

<%= link_to 'Back', custom_campaigns_path %>

app/views/custom_campaigns/show.html.erb
<p id="notice"><%= notice %></p>

<p>
  <strong>Name:</strong>
  <%= @custom_campaign.name %>
</p>

<p>
  <strong>Description:</strong>
  <%= @custom_campaign.description %>
</p>

<p>
  <strong>Company:</strong>
  <%= @custom_campaign.company %>
</p>

<p>
  <strong>Start date:</strong>
  <%= @custom_campaign.start_date %>
</p>

<p>
  <strong>End date:</strong>
  <%= @custom_campaign.end_date %>
</p>

<p>
  <strong>Notes:</strong>
  <%= @custom_campaign.notes %>
</p>

<p>
  <strong>Num images required:</strong>
  <%= @custom_campaign.num_images_required %>
</p>

<%= link_to 'Edit', edit_custom_campaign_path(@custom_campaign) %> |
<%= link_to 'Back', custom_campaigns_path %>