config/routes.rb
Rails.application.routes.draw do
  resources :affars
  resources :koncepts
  resources :kedjas
  resources :excel_to_model_mappings
  resources :uploaded_files
  resources :products
  resources :custom_campaigns
  get 'welcome/index'

  resources :people
  resources :companies

  root 'welcome#index'

end

app/models/company.rb
class Company < ActiveRecord::Base
	has_many :people, dependent: :destroy
end

app/controllers/companies_controller.rb
class CompaniesController < ApplicationController
  before_action :set_company, only: [:show, :edit, :update, :destroy]

  # GET /companies
  # GET /companies.json
  def index
    @companies = Company.all
  end

  # GET /companies/1
  # GET /companies/1.json
  def show
  end

  # GET /companies/new
  def new
    @company = Company.new
  end

  # GET /companies/1/edit
  def edit
  end

  # POST /companies
  # POST /companies.json
  def create
    @company = Company.new(company_params)

    respond_to do |format|
      if @company.save
        format.html { redirect_to @company, notice: 'Company was successfully created.' }
        format.json { render :show, status: :created, location: @company }
      else
        format.html { render :new }
        format.json { render json: @company.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /companies/1
  # PATCH/PUT /companies/1.json
  def update
    respond_to do |format|
      if @company.update(company_params)
        format.html { redirect_to @company, notice: 'Company was successfully updated.' }
        format.json { render :show, status: :ok, location: @company }
      else
        format.html { render :edit }
        format.json { render json: @company.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /companies/1
  # DELETE /companies/1.json
  def destroy
    @company.destroy
    respond_to do |format|
      format.html { redirect_to companies_url, notice: 'Company was successfully destroyed.' }
      format.json { head :no_content }
    end
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_company
      @company = Company.find(params[:id])
    end

    # Never trust parameters from the scary internet, only allow the white list through.
    def company_params
      params.require(:company).permit(:name, :business_id, :home_page)
    end
end

app/helpers/companies_helper.rb
module CompaniesHelper
end

app/views/companies/_form.html.erb
<%= bootstrap_form_for(@company, layout: :horizontal, label_col: "col-sm-2", control_col: "col-sm-10") do |f| %>
<fieldset>
    <legend>Legend</legend>
  <% if @company.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(@company.errors.count, "error") %> prohibited this company from being saved:</h2>

      <ul>
      <% @company.errors.full_messages.each do |message| %>
        <li><%= message %></li>
      <% end %>
      </ul>
    </div>
  <% end %>

  
    <%= f.text_field :name %>
    <%= f.number_field :business_id %>
    <%= f.text_field :home_page %>
    <%= f.submit %>
    </fieldset>
<% end %>

app/views/companies/edit.html.erb
<h1>Editing Company</h1>

<%= render 'form' %>

<%= link_to 'Show', @company %> |
<%= link_to 'Back', companies_path %>

app/views/companies/index.html.erb
<p id="notice"><%= notice %></p>

<h1>Listing Companies</h1>

<table class="table table-striped table-hover">
  <thead>
    <tr>
      <th>Name</th>
      <th>Business</th>
      <th>Home page</th>
      <th colspan="3"></th>
    </tr>
  </thead>

  <tbody>
    <% @companies.each do |company| %>
      <tr class="active">
        <td><%= company.name %></td>
        <td><%= company.business_id %></td>
        <td><%= company.home_page %></td>
        <td><%= link_to 'Show', company %></td>
        <td><%= link_to 'Edit', edit_company_path(company) %></td>
        <td><%= link_to 'Destroy', company, method: :delete, data: { confirm: 'Are you sure?' } %></td>
      </tr>
    <% end %>
  </tbody>
</table>

<br>

<%= link_to 'New Company', new_company_path, class: "btn btn-default" %>

app/views/companies/new.html.erb
<h1>New Company</h1>

<%= render 'form' %>

<%= link_to 'Back', companies_path %>

app/views/companies/show.html.erb
<p id="notice"><%= notice %></p>

<p>
  <strong>Name:</strong>
  <%= @company.name %>
</p>

<p>
  <strong>Business:</strong>
  <%= @company.business_id %>
</p>

<p>
  <strong>Home page:</strong>
  <%= @company.home_page %>
</p>

<h3>People</h3>

<% @company.people.each do |person|%>
      <tr>
        <td><%= person.first_name %></td>
        <td><%= person.last_name %></td>
        <td><%= person.email %></td>
        <td><%= person.telephone %></td>
        <td><%= person.address %></td>
        <td><%= link_to 'Show', person %></td>
        <td><%= link_to 'Edit', edit_person_path(person) %></td>
        <td><%= link_to 'Destroy', person, method: :delete, data: { confirm: 'Are you sure?' } %></td>
      </tr>
<% end%>

<%= link_to 'Edit', edit_company_path(@company) %> |
<%= link_to 'Back', companies_path %>